version: '3.7'

services:
  server:
    build:
      context: ./nginx-server
      dockerfile: Dockerfile
    ports:
      - 5001:5000
      - 80:80
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

