apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  initdb.sql: |
    CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres'; 
    CREATE ROLE postgres;
    CREATE DATABASE hosts;
    CREATE DATABASE postgres WITH OWNER postgres;
    GRANT ALL PRIVILEGES ON DATABASE hosts TO postgres;
    CREATE TABLE IF NOT EXISTS hosts (
      id SERIAL PRIMARY KEY,
      host_name varchar(45),
      ip_address varchar(45),
      uptime varchar(45)
    )


